# Generated by Django 3.2.15 on 2022-09-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220906_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingdetails',
            name='address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
