# Generated by Django 3.2.15 on 2022-09-07 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220906_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingdetails',
            old_name='paid',
            new_name='completed',
        ),
        migrations.RemoveField(
            model_name='shippingdetails',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='shippingdetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
    ]
